# Generated by Django 4.0.4 on 2022-07-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_module', '0002_gallery_owner_userartwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='material',
            field=models.CharField(default='سیاه قلم', max_length=200, verbose_name='متریال'),
        ),
    ]
