# Generated by Django 4.0.4 on 2022-07-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_module', '0003_gallery_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='size',
            field=models.CharField(default='30*40', max_length=200, verbose_name='سایز'),
        ),
    ]
