# Generated by Django 4.0.4 on 2022-07-05 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_module', '0004_gallery_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='date',
            new_name='created_at',
        ),
    ]
