# Generated by Django 4.0.4 on 2022-07-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery_module', '0005_rename_date_gallery_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='description',
            field=models.TextField(default='', verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='تخفیف'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='fourth_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/gallery/', verbose_name='تصویر چهارم'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='price',
            field=models.IntegerField(default=0, verbose_name='قیمت'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/gallery/', verbose_name='تصویر دوم'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='third_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/gallery/', verbose_name='تصویر سوم'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='static/img/gallery/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نمایش در زیر صفحه '),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
    ]
