# Generated by Django 4.0.4 on 2022-06-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0002_alter_courses_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='payment_receipt_file',
            field=models.FileField(blank=True, upload_to='static/img/receipts', verbose_name='رسید پرداخت'),
        ),
    ]
