# Generated by Django 4.0.4 on 2022-06-14 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0003_usercourse_payment_receipt_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='payment_receipt_file',
        ),
    ]
