# Generated by Django 4.0.4 on 2022-06-20 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_module', '0004_remove_usercourse_payment_receipt_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAndAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(db_index=True, max_length=200, verbose_name='سوال')),
                ('answer', models.CharField(max_length=200, verbose_name='پاسخ')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('is_approved', models.BooleanField(db_index=True, default=False, verbose_name='تایید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_module.courses', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'پرسش و پاسخ',
                'verbose_name_plural': 'سوال و پاسخ',
            },
        ),
    ]
